In [4]:
import pandas as pd
import numpy as np

In [5]:
train_df = pd.read_csv('/content/drive/MyDrive/PROYECT_6/train_df.csv')

In [6]:
test_df = pd.read_csv('/content/drive/MyDrive/PROYECT_6/test_df.csv')

In [7]:
train_df.head()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,day,hour,count
0,3,0,1,1,27.88,31.820,83,6.0032,2011,7,6,5,35
1,3,0,0,1,36.90,40.910,39,19.9995,2012,8,4,16,450
2,3,0,1,1,32.80,35.605,41,16.9979,2012,7,11,15,276
3,2,0,0,2,14.76,18.180,93,7.0015,2011,4,10,4,5
4,4,0,0,1,13.12,15.150,45,16.9979,2011,11,19,10,200

In [8]:
test_df.head()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,day,hour,count
0,3,0,1,1,33.62,40.150,59,0.0000,2011,7,19,11,127
1,1,1,0,1,4.10,6.820,54,6.0032,2012,1,16,6,13
2,4,0,0,1,9.84,11.365,48,12.9980,2011,12,11,18,163
3,3,0,1,2,29.52,34.090,62,12.9980,2012,8,15,10,233
4,2,0,1,1,25.42,31.060,53,16.9979,2012,6,15,23,222

In [9]:
train_df.shape

(8708, 13)

In [10]:
test_df.shape

(2178, 13)

In [14]:
X_train = train_df.drop('count', axis=1)
y_train = train_df['count']

X_test = test_df.drop('count', axis=1)
y_test = test_df['count']

In [15]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(8708, 12) (2178, 12)
(8708,) (2178,)

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [19]:
from sklearn.pipeline import Pipeline

In [20]:
models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'XGBoost': XGBRegressor()
}

In [22]:
for name, model in models.items():
  pipeline = Pipeline([
      ('model', model)
  ])

  pipeline.fit(X_train, y_train)

  y_pred = pipeline.predict(X_test)

  mse = mean_squared_error(y_test, y_pred)
  mae = mean_absolute_error(y_test, y_pred)
  r2 = r2_score(y_test, y_pred)

  print(f'{name}:')
  print(f'MSE: {mse}')
  print(f'MAE: {mae}')
  print(f'R2: {r2}')
  print('-'*30)

Linear Regression:
MSE: 19945.370053754057
MAE: 105.34191529221637
R2: 0.3957218526642545
------------------------------
Random Forest:
MSE: 1805.6873927456381
MAE: 27.161983471074382
R2: 0.9452936982660557
------------------------------
Decision Tree:
MSE: 3691.497245179063
MAE: 37.10973370064279
R2: 0.8881599534027217
------------------------------
XGBoost:
MSE: 1590.4501953125
MAE: 26.412124633789062
R2: 0.9518146514892578
------------------------------

In [27]:
best_model = Pipeline([
    ('model', XGBRegressor())
])

In [28]:
best_model.fit(X_train, y_train)

Pipeline(steps=[('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=True, eval_metric=None,
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [29]:
import joblib

In [30]:
joblib.dump(best_model, '/content/drive/MyDrive/PROYECT_6/best_model.pkl')

['/content/drive/MyDrive/PROYECT_6/best_model.pkl']